// <auto-generated />
using System;
using CampaignManager.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampaignManager.Data.Migrations
{
    [DbContext(typeof(CampaignDbContext))]
    partial class CampaignDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampaignManager.Shared.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Channels")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsSchedulerEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("NextScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.ToTable("Campaigns");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            Channels = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "A sample email campaign for demonstration",
                            IsSchedulerEnabled = false,
                            Name = "Demo Email Campaign",
                            ProjectId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Status = 0
                        });
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.CampaignApiConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailSubject")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EmailTemplateHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParameterMappings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SendGridApiKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SendGridFromEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SendGridFromName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SendGridTemplateId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SmsAccountSid")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SmsApiEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SmsApiKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SmsAuthToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SmsFromNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SmsTemplate")
                        .HasMaxLength(1600)
                        .HasColumnType("nvarchar(1600)");

                    b.Property<string>("TokenGenerationConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VoiceBlastApiEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("VoiceBlastApiKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VoiceBlastCampaignId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VoiceBlastMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoiceBlastParameterMappings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebExApiEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WebExAuthToken")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("WebExCurl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("WhatsAppAccountSid")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WhatsAppApiEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WhatsAppApiKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("WhatsAppAuthToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WhatsAppFromNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WhatsAppTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatsAppTemplateName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .IsUnique();

                    b.ToTable("CampaignApiConfigs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000050"),
                            CampaignId = new Guid("00000000-0000-0000-0000-000000000030"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SendGridFromEmail = "noreply@demo.local",
                            SendGridFromName = "Demo Campaign"
                        });
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.CampaignField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FieldType")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "FieldName")
                        .IsUnique();

                    b.ToTable("CampaignFields");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000040"),
                            CampaignId = new Guid("00000000-0000-0000-0000-000000000030"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "First Name",
                            DisplayOrder = 1,
                            FieldName = "firstName",
                            FieldType = 0,
                            IsRequired = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000041"),
                            CampaignId = new Guid("00000000-0000-0000-0000-000000000030"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Last Name",
                            DisplayOrder = 2,
                            FieldName = "lastName",
                            FieldType = 0,
                            IsRequired = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000042"),
                            CampaignId = new Guid("00000000-0000-0000-0000-000000000030"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Email Address",
                            DisplayOrder = 3,
                            FieldName = "email",
                            FieldType = 4,
                            IsRequired = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000043"),
                            CampaignId = new Guid("00000000-0000-0000-0000-000000000030"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Phone Number",
                            DisplayOrder = 4,
                            FieldName = "phone",
                            FieldType = 5,
                            IsRequired = false
                        });
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.CampaignLead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedAgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CallAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CallConnectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CallStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmailAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmailStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastCallAttemptAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastEmailAttemptAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextScheduledAction")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAgentId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("NextScheduledAction");

                    b.HasIndex("Status");

                    b.ToTable("CampaignLeads");
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.CampaignStrategy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan?>("CallEndTime")
                        .HasColumnType("time");

                    b.Property<int>("CallRetryIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("CallStartTime")
                        .HasColumnType("time");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmailRetryIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MaxCallAttempts")
                        .HasColumnType("int");

                    b.Property<int>("MaxEmailAttempts")
                        .HasColumnType("int");

                    b.Property<int>("MaxSmsAttempts")
                        .HasColumnType("int");

                    b.Property<int>("MaxVoiceBlastAttempts")
                        .HasColumnType("int");

                    b.Property<int>("MaxWhatsAppAttempts")
                        .HasColumnType("int");

                    b.Property<int>("SmsRetryIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<string>("StrategyRulesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VoiceBlastRetryIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<int>("WhatsAppRetryIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<string>("WorkingDays")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .IsUnique();

                    b.ToTable("CampaignStrategies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000051"),
                            CallRetryIntervalMinutes = 60,
                            CampaignId = new Guid("00000000-0000-0000-0000-000000000030"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailRetryIntervalMinutes = 1440,
                            MaxCallAttempts = 5,
                            MaxEmailAttempts = 3,
                            MaxSmsAttempts = 3,
                            MaxVoiceBlastAttempts = 3,
                            MaxWhatsAppAttempts = 3,
                            SmsRetryIntervalMinutes = 60,
                            VoiceBlastRetryIntervalMinutes = 30,
                            WhatsAppRetryIntervalMinutes = 60,
                            WorkingDays = "Mon,Tue,Wed,Thu,Fri"
                        });
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SentAt");

                    b.HasIndex("SenderId", "ReceiverId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.Disposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsQualified")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequiresCallback")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProjectId", "Code")
                        .IsUnique()
                        .HasFilter("[ProjectId] IS NOT NULL");

                    b.ToTable("Dispositions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            Code = "QUALIFIED",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsQualified = true,
                            Name = "Qualified Lead",
                            ProjectId = new Guid("00000000-0000-0000-0000-000000000010"),
                            RequiresCallback = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            Code = "NOT_INTERESTED",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            IsQualified = false,
                            Name = "Not Interested",
                            ProjectId = new Guid("00000000-0000-0000-0000-000000000010"),
                            RequiresCallback = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            Code = "CALLBACK",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            IsQualified = false,
                            Name = "Callback Required",
                            ProjectId = new Guid("00000000-0000-0000-0000-000000000010"),
                            RequiresCallback = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            Code = "NO_ANSWER",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsActive = true,
                            IsQualified = false,
                            Name = "No Answer",
                            ProjectId = new Guid("00000000-0000-0000-0000-000000000010"),
                            RequiresCallback = true
                        });
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.LeadDisposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CallbackDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DisposedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DispositionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubDispositionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DisposedById");

                    b.HasIndex("LeadId")
                        .IsUnique();

                    b.ToTable("LeadDispositions");
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.License", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaxCampaigns")
                        .HasColumnType("int");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LicenseKey")
                        .IsUnique();

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("Licenses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            ActivatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiryDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActivated = true,
                            LicenseKey = "DEMO-1234-5678-ABCD",
                            MaxCampaigns = 10,
                            MaxUsers = 50,
                            ProjectId = new Guid("00000000-0000-0000-0000-000000000010")
                        });
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A sample project for demonstration purposes",
                            IsActive = true,
                            Name = "Demo Project"
                        });
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid?>("SupervisorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@campaignmanager.local",
                            FirstName = "Super",
                            IsActive = true,
                            IsOnline = false,
                            LastName = "Admin",
                            PasswordHash = "$2a$11$WCDqnEksHWQsG7Za1KfMue9sOUHGRPWPV3GKL93AYQcJzIn8oU7ui",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "subadmin@demo.local",
                            FirstName = "Sub",
                            IsActive = true,
                            IsOnline = false,
                            LastName = "Admin",
                            PasswordHash = "$2a$11$wbeagR.onmQYakqSy5tEqO4z6U.E4JCFqndvYL.6OG5hNj6xsKcfi",
                            ProjectId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "supervisor@demo.local",
                            FirstName = "Demo",
                            IsActive = true,
                            IsOnline = false,
                            LastName = "Supervisor",
                            PasswordHash = "$2a$11$pDgWTkRfzZfrKuxJila8u.X6fzxr1K.PFbdkgQrEl5vGHqovzlr1e",
                            ProjectId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "agent@demo.local",
                            FirstName = "Demo",
                            IsActive = true,
                            IsOnline = false,
                            LastName = "Agent",
                            PasswordHash = "$2a$11$CTCCNGRvH2t2mMI7eW0KCOm0w7RUq3mm/6WTulJ22y0NBz38mlez6",
                            ProjectId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Role = 3,
                            SupervisorId = new Guid("00000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.Campaign", b =>
                {
                    b.HasOne("CampaignManager.Shared.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("CampaignManager.Shared.Models.Project", "Project")
                        .WithMany("Campaigns")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.CampaignApiConfig", b =>
                {
                    b.HasOne("CampaignManager.Shared.Models.Campaign", "Campaign")
                        .WithOne("ApiConfig")
                        .HasForeignKey("CampaignManager.Shared.Models.CampaignApiConfig", "CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.CampaignField", b =>
                {
                    b.HasOne("CampaignManager.Shared.Models.Campaign", "Campaign")
                        .WithMany("Fields")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.CampaignLead", b =>
                {
                    b.HasOne("CampaignManager.Shared.Models.User", "AssignedAgent")
                        .WithMany()
                        .HasForeignKey("AssignedAgentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CampaignManager.Shared.Models.Campaign", "Campaign")
                        .WithMany("Leads")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedAgent");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.CampaignStrategy", b =>
                {
                    b.HasOne("CampaignManager.Shared.Models.Campaign", "Campaign")
                        .WithOne("Strategy")
                        .HasForeignKey("CampaignManager.Shared.Models.CampaignStrategy", "CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.ChatMessage", b =>
                {
                    b.HasOne("CampaignManager.Shared.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignManager.Shared.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.Disposition", b =>
                {
                    b.HasOne("CampaignManager.Shared.Models.Disposition", "Parent")
                        .WithMany("SubDispositions")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampaignManager.Shared.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.Navigation("Parent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.LeadDisposition", b =>
                {
                    b.HasOne("CampaignManager.Shared.Models.User", "DisposedBy")
                        .WithMany()
                        .HasForeignKey("DisposedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CampaignManager.Shared.Models.CampaignLead", "Lead")
                        .WithOne("Disposition")
                        .HasForeignKey("CampaignManager.Shared.Models.LeadDisposition", "LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DisposedBy");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.License", b =>
                {
                    b.HasOne("CampaignManager.Shared.Models.Project", "Project")
                        .WithOne("License")
                        .HasForeignKey("CampaignManager.Shared.Models.License", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.User", b =>
                {
                    b.HasOne("CampaignManager.Shared.Models.Project", "Project")
                        .WithMany("Users")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CampaignManager.Shared.Models.User", "Supervisor")
                        .WithMany("Subordinates")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Project");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.Campaign", b =>
                {
                    b.Navigation("ApiConfig");

                    b.Navigation("Fields");

                    b.Navigation("Leads");

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.CampaignLead", b =>
                {
                    b.Navigation("Disposition");
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.Disposition", b =>
                {
                    b.Navigation("SubDispositions");
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.Project", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("License");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CampaignManager.Shared.Models.User", b =>
                {
                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
